<a href="https://colab.research.google.com/github/manishhegde/Bike-Case-study/blob/main/house_price_transors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [5]:
df= pd.read_csv('/content/house_price_full+(2).csv')
df.head()

bedrooms  sqft_living    price
0         3         1340   313000
1         5         3650  2384000
2         3         1930   342000
3         3         2000   420000
4         4         1940   550000

In [6]:
X = df.copy()
# Remove target
Y = X.pop('price')

# perform a scaler transform of the input data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# perform log transformation of target variable (For Sandeep: Is this needed?)
Y = np.log(Y)

In [7]:
df_scaled = pd.DataFrame(X)
df_scaled

0         1
0   -0.433198 -0.753258
1    1.675735  1.457330
2   -0.433198 -0.188649
3   -0.433198 -0.121661
4    0.621269 -0.179079
..        ...       ...
494  0.621269  0.873582
495  1.675735  2.299459
496 -0.433198 -0.724549
497 -0.433198 -0.179079
498 -0.433198 -1.040347

[499 rows x 2 columns]

In [8]:
Y

0      12.653958
1      14.684290
2      12.742566
3      12.948010
4      13.217674
         ...    
494    13.380102
495    13.764217
496    12.128111
497    12.721886
498    12.254863
Name: price, Length: 499, dtype: float64

In [9]:
#Taking 1 sample: x0,x1
x1, x2 = df_scaled.iloc[0]

In [10]:
x = tf.constant([[x1,x2]], dtype=tf.float32)
x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.43319765, -0.7532575 ]], dtype=float32)>

In [11]:
#weights
w1 = tf.Variable([0.2], dtype=tf.float32)
w2 = tf.Variable([0.15], dtype=tf.float32)
#bias
b = tf.Variable([0.1], dtype=tf.float32)

In [12]:
#Cumulative input
z = b + w1*x1 +w2*x2
h = tf.math.sigmoid(z)
print("The output from the first neuron is",h)

The output from the first neuron is tf.Tensor([0.47511354], shape=(1,), dtype=float32)


In [13]:
## layer1 weights
# neuron1
b1 = tf.Variable([0.1])
w11 = tf.Variable([0.2])
w12 = tf.Variable([0.15])
#neuron2
b2 = tf.Variable([0.25])
w21 = tf.Variable([0.5])
w22 = tf.Variable([0.6])

In [14]:
## forward pass
# neuron 1
z1 = b1+w11*x1+w12*x2
h1 = tf.math.sigmoid(z1)
print("The output from the first neuron is",h1)

The output from the first neuron is tf.Tensor([0.47511354], shape=(1,), dtype=float32)


In [15]:
## forward pass
# neuron 2
z2 = b2+w21*x1+w22*x2
h2 = tf.math.sigmoid(z2)
print("The output from the second neuron is",h2)

The output from the second neuron is tf.Tensor([0.39686298], shape=(1,), dtype=float32)


In [16]:
## layer2 weights
b1 = tf.Variable([0.4])
w11 = tf.Variable([0.3])
w12 = tf.Variable([0.2])

In [17]:
## forward pass
# second layer
z1 = b1+w11*h1+w12*h2
h1 = z1
print("The output from the first neuron is",h1)

The output from the first neuron is tf.Tensor([0.62190664], shape=(1,), dtype=float32)


In [18]:
y_true = Y[0]
y_pred = h1.numpy()

In [19]:
#loss
L = 0.5*(y_true - y_pred)**2
print("The MSE error is",L)

The MSE error is [72.38514]


In [20]:
## layer 1 weights
W1 = tf.Variable([[0.2, 0.15],
                     [0.5, 0.6]], dtype=tf.float32)
## layer 1 bias
B1 = tf.Variable([[0.1],
                [0.25]], dtype=tf.float32)

In [21]:
## layer 2 weights
W2 = tf.Variable([[0.3, 0.2]], dtype=tf.float32)
#bias
B2 = tf.Variable([0.4], dtype=tf.float32)

In [22]:
## data
X = tf.constant([[x1,x2]], dtype=tf.float32)

In [23]:
## forward pass layer 1
Z1 = tf.matmul(W1, tf.transpose(X)) + B1
H1 = tf.math.sigmoid(Z1)
print(H1)

tf.Tensor(
[[0.47511354]
 [0.39686298]], shape=(2, 1), dtype=float32)


In [24]:
## forward pass layer 2
Z2 = tf.matmul(W2,H1)+B2

In [25]:
Z2


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.62190664]], dtype=float32)>

In [26]:
y_pred = Z2.numpy()
loss = 0.5*(y_true-y_pred)**2
print(loss)

[[72.38514]]


In [27]:
def random_init_params():
    w1 = tf.Variable(tf.random.uniform((2, 2)))
    b1 = tf.Variable(tf.random.uniform((1, 2)))
    w2 = tf.Variable(tf.random.uniform((2, 1)))
    b2 = tf.Variable(tf.random.uniform((1, 1)))
    return w1,b1,w2,b2

In [28]:
x = tf.constant([[x1,x2]], dtype=tf.float32)
y = Y[0]
w1,b1,w2,b2 = random_init_params()

In [29]:
print(" the initial 1st layer weights are:\n",w1.numpy())
print("--------------------------------------------------")
print(" the initial 2nd layer weights are:\n",w2.numpy())
print("--------------------------------------------------")
print(" the initial 1st layer bias are:\n",b1.numpy())
print("--------------------------------------------------")
print(" the initial 2nd layer bias are:\n",b2.numpy())

 the initial 1st layer weights are:
 [[0.42173088 0.8742763 ]
 [0.52026093 0.8608177 ]]
--------------------------------------------------
 the initial 2nd layer weights are:
 [[0.10926247]
 [0.33330846]]
--------------------------------------------------
 the initial 1st layer bias are:
 [[0.16138673 0.39051878]]
--------------------------------------------------
 the initial 2nd layer bias are:
 [[0.6156781]]


In [30]:
def forward_prop(x, w1, b1, w2, b2):
    z1 = tf.matmul(x,w1) + b1
    h1 = tf.math.sigmoid(z1)
    z2 = tf.matmul(h1,w2) + b2
    h2 = z2
    return h2

In [31]:
y_pred = forward_prop(x, w1, b1, w2, b2)
#loss
L = 0.5*(y - y_pred)**2
print("The MSE error is",L)

The MSE error is tf.Tensor([[70.56068]], shape=(1, 1), dtype=float32)


In [32]:
x = tf.Variable(0.0) ## add gradient tape
lr = eta = 0.1

In [33]:
with tf.GradientTape() as tape:
    y = x**2+4*x
grad = tape.gradient(y,x) ## dy/dx

In [34]:
grad.numpy() #dy/dx = 2x+4, x=0 => dy/dx = 4

4.0

In [ ]:
x.assign_sub(lr*grad) ## x_new = x_old -lr*dy/dx

In [35]:
x.numpy()

0.0

In [36]:
## full loop
x = tf.Variable(0.0) ## add gradient tape
lr = eta = 0.1
for i in range(10):
    with tf.GradientTape() as tape:
        y = x**2+4*x
    grad = tape.gradient(y,x)
    x.assign_sub(lr*grad)
    print(x.numpy())

-0.4
-0.72
-0.9760001
-1.1808001
-1.34464
-1.4757121
-1.5805696
-1.6644557
-1.7315645
-1.7852516


In [37]:
x = tf.constant([[x1,x2]], dtype=tf.float32)
y = Y[0]

def random_init_params():
    w1 = tf.Variable(tf.random.uniform((2, 2)))
    b1 = tf.Variable(tf.random.uniform((1, 2)))
    w2 = tf.Variable(tf.random.uniform((2, 1)))
    b2 = tf.Variable(tf.random.uniform((1, 1)))
    return w1,b1,w2,b2

def forward_prop(x, w1, b1, w2, b2):
    z1 = tf.matmul(x,w1) + b1
    h1 = tf.math.sigmoid(z1)
    z2 = tf.matmul(h1,w2) + b2
    h2 = z2
    return h2

In [38]:
w1,b1,w2,b2 = random_init_params()

In [39]:
with tf.GradientTape() as tape:
    y_pred = forward_prop(x,w1,b1,w2,b2)
    loss = 0.5*(y-y_pred)**2

In [40]:
gw1, gb1, gw2, gb2 = tape.gradient(loss, [w1, b1, w2, b2])

In [41]:
gw1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.91615397, 0.0603701 ],
       [1.5930369 , 0.10497341]], dtype=float32)>

In [42]:
gb1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-2.1148636 , -0.13935925]], dtype=float32)>

In [43]:
gw2

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-4.845791],
       [-6.177396]], dtype=float32)>

In [44]:
gb2


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-11.897734]], dtype=float32)>

In [46]:
lr=0.01
print(f"Value of w1 before gradient update is {w1}")
w1.assign_sub(lr*gw1)
print(f"Value of w1 after gradient update is {w1}")

Value of w1 before gradient update is <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.35230267, 0.8693981 ],
       [0.5514364 , 0.06832063]], dtype=float32)>
Value of w1 after gradient update is <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.34314114, 0.86879444],
       [0.53550607, 0.0672709 ]], dtype=float32)>


In [47]:
lr=0.01
print(f"Value of b1 before gradient update is {b1}")
b1.assign_sub(lr*gb1)
print(f"Value of w1 after gradient update is {b1}")

Value of b1 before gradient update is <tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0.19279754, 0.50495327]], dtype=float32)>
Value of w1 after gradient update is <tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0.21394618, 0.5063469 ]], dtype=float32)>


In [48]:
def train(x, y, w1, b1, w2, b2):
    y_true = y
    with tf.GradientTape() as g:
        y_pred = forward_prop(x, w1, b1, w2, b2)

        # loss
        loss = 0.5*(y_true - y_pred)** 2
    
    #Gradient calculation  
    print("**************************************************")
    print("GRADIENTS")
    print("**************************************************")
    gw1, gb1, gw2, gb2 = g.gradient(loss, [w1, b1, w2, b2])
    print(" the gradient for 1st layer weights are:\n",gw1.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 2nd layer weights are:\n",gw2.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 1st layer bias are:\n",gb1.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 2nd layer bias are:\n",gb2.numpy())
    print("--------------------------------------------------")

    # Gradient descent:
    lr=0.2
    w1.assign_sub(lr*gw1)
    b1.assign_sub(lr*gb1) 
    w2.assign_sub(lr*gw2)
    b2.assign_sub(lr*gb2)
    print("**************************************************")
    print("NEW UPDATES")
    print("**************************************************")
    print(" the updated 1st layer weights are:\n",w1.numpy())
    print("--------------------------------------------------")
    print(" the updated 2nd layer weights are:\n",w2.numpy())
    print("--------------------------------------------------")
    print(" the updated 1st layer bias are:\n",b1.numpy())
    print("--------------------------------------------------")
    print(" the updated 2nd layer bias are:\n",b2.numpy())


    return w1, b1, w2, b2,loss

In [49]:
w1,b1,w2,b2 = random_init_params()
w1, b1, w2, b2,loss = train(x, y, w1, b1, w2, b2)

**************************************************
GRADIENTS
**************************************************
 the gradient for 1st layer weights are:
 [[0.05034444 0.58845335]
 [0.08754047 1.0232209 ]]
--------------------------------------------------
 the gradient for 2nd layer weights are:
 [[-7.082007]
 [-4.810186]]
--------------------------------------------------
 the gradient for 1st layer bias are:
 [[-0.11621586 -1.3583946 ]]
--------------------------------------------------
 the gradient for 2nd layer bias are:
 [[-11.759512]]
--------------------------------------------------
**************************************************
NEW UPDATES
**************************************************
 the updated 1st layer weights are:
 [[ 0.05355204  0.5384011 ]
 [ 0.61012334 -0.08125304]]
--------------------------------------------------
 the updated 2nd layer weights are:
 [[1.4576571]
 [1.4399083]]
--------------------------------------------------
 the updated 1st layer bias a